2014/10/14 12:04:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\Yii2\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Yii2\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii2/testdrive/index.php?r=gii
---
2014/10/14 12:23:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Dependecia".' in C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(141): CWebApplication->runController('Dependecia')
#1 C:\xampp\htdocs\Yii2\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Yii2\testdrive\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii2/testdrive/index.php?r=Dependecia
---
2014/10/14 13:09:07 [error] [exception.CException] exception 'CException' with message 'Property "ContactForm.nombre" is not defined.' in C:\xampp\htdocs\Yii2\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Yii2\framework\web\helpers\CHtml.php(2529): CComponent->__get('nombre')
#1 C:\xampp\htdocs\Yii2\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(ContactForm), 'nombre')
#2 C:\xampp\htdocs\Yii2\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(ContactForm), 'nombre', Array)
#3 C:\xampp\htdocs\Yii2\framework\web\widgets\CActiveForm.php(725): CHtml::activeTextField(Object(ContactForm), 'nombre', Array)
#4 C:\xampp\htdocs\Yii2\testdrive\protected\views\site\contact.php(42): CActiveForm->textField(Object(ContactForm), 'nombre')
#5 C:\xampp\htdocs\Yii2\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\Yii2\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\Yii2\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\Yii2\framework\web\CController.php(782): CController->renderPartial('contact', Array, true)
#9 C:\xampp\htdocs\Yii2\testdrive\protected\controllers\SiteController.php(72): CController->render('contact', Array)
#10 C:\xampp\htdocs\Yii2\framework\web\actions\CInlineAction.php(49): SiteController->actionContact()
#11 C:\xampp\htdocs\Yii2\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\Yii2\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\Yii2\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(282): CController->run('contact')
#15 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contact')
#16 C:\xampp\htdocs\Yii2\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\Yii2\testdrive\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/yii2/testdrive/index.php?r=site/contact
HTTP_REFERER=http://127.0.0.1/yii2/testdrive/index.php?r=site/page&view=about
---
2014/10/14 13:29:12 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii2\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii2\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii2\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii2\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii2\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii2\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(141): CWebApplication->runController('paciente/admin')
#9 C:\xampp\htdocs\Yii2\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Yii2\testdrive\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii2/testdrive/index.php?r=paciente/admin
HTTP_REFERER=http://127.0.0.1/yii2/testdrive/index.php
---
2014/10/14 13:29:16 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii2\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii2\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii2\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii2\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii2\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii2\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(141): CWebApplication->runController('paciente/admin')
#9 C:\xampp\htdocs\Yii2\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Yii2\testdrive\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii2/testdrive/index.php?r=paciente/admin
HTTP_REFERER=http://127.0.0.1/yii2/testdrive/index.php?r=paciente/admin
---
2014/10/14 13:29:17 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii2\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii2\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii2\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii2\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii2\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii2\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(141): CWebApplication->runController('sala/admin')
#9 C:\xampp\htdocs\Yii2\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Yii2\testdrive\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii2/testdrive/index.php?r=sala/admin
HTTP_REFERER=http://127.0.0.1/yii2/testdrive/index.php?r=paciente/admin
---
2014/10/14 13:29:17 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii2\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii2\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii2\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii2\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii2\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii2\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(141): CWebApplication->runController('dependencia/adm...')
#9 C:\xampp\htdocs\Yii2\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Yii2\testdrive\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii2/testdrive/index.php?r=dependencia/admin
HTTP_REFERER=http://127.0.0.1/yii2/testdrive/index.php?r=sala/admin
---
2014/10/14 13:29:18 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii2\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii2\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii2\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii2\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii2\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii2\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/admin')
#9 C:\xampp\htdocs\Yii2\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Yii2\testdrive\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii2/testdrive/index.php?r=usuario/admin
HTTP_REFERER=http://127.0.0.1/yii2/testdrive/index.php?r=dependencia/admin
---
2014/10/14 13:29:19 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii2\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii2\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii2\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii2\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii2\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii2\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(141): CWebApplication->runController('riesgo/admin')
#9 C:\xampp\htdocs\Yii2\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Yii2\testdrive\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii2/testdrive/index.php?r=riesgo/admin
HTTP_REFERER=http://127.0.0.1/yii2/testdrive/index.php?r=usuario/admin
---
2014/10/14 13:29:21 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii2\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii2\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii2\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii2\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii2\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii2\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(141): CWebApplication->runController('cama/admin')
#9 C:\xampp\htdocs\Yii2\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Yii2\testdrive\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii2/testdrive/index.php?r=cama/admin
HTTP_REFERER=http://127.0.0.1/yii2/testdrive/index.php?r=riesgo/admin
---
2014/10/14 13:29:22 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii2\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii2\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii2\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii2\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii2\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii2\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(141): CWebApplication->runController('dependencia/adm...')
#9 C:\xampp\htdocs\Yii2\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Yii2\testdrive\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii2/testdrive/index.php?r=dependencia/admin
HTTP_REFERER=http://127.0.0.1/yii2/testdrive/index.php?r=cama/admin
---
2014/10/14 13:29:23 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii2\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii2\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii2\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii2\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii2\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii2\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/admin')
#9 C:\xampp\htdocs\Yii2\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Yii2\testdrive\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii2/testdrive/index.php?r=usuario/admin
HTTP_REFERER=http://127.0.0.1/yii2/testdrive/index.php?r=dependencia/admin
---
2014/10/14 13:29:23 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii2\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii2\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii2\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii2\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii2\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii2\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii2\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii2\framework\web\CWebApplication.php(141): CWebApplication->runController('riesgo/admin')
#9 C:\xampp\htdocs\Yii2\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Yii2\testdrive\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii2/testdrive/index.php?r=riesgo/admin
HTTP_REFERER=http://127.0.0.1/yii2/testdrive/index.php?r=usuario/admin
---
2014/10/14 14:35:01 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'camas'' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Paciente))
#7 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Yii\test\protected\controllers\PacienteController.php(136): CActiveRecord->__construct('search')
#9 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): PacienteController->actionAdmin()
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('admin')
#19 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('paciente/admin')
#20 C:\xampp\htdocs\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Yii\test\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/yii/test/index.php?r=paciente/admin
HTTP_REFERER=http://localhost:200/yii/test/index.php?r=site/login
---
2014/10/14 14:35:12 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'camas'' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Dependencia))
#7 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Yii\test\protected\controllers\DependenciaController.php(136): CActiveRecord->__construct('search')
#9 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): DependenciaController->actionAdmin()
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('admin')
#19 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dependencia/adm...')
#20 C:\xampp\htdocs\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Yii\test\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/yii/test/index.php?r=dependencia/admin
HTTP_REFERER=http://localhost:200/yii/test/index.php?r=site/login
---
2014/10/14 14:37:04 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'camas'' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Cama))
#7 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Yii\test\protected\controllers\CamaController.php(136): CActiveRecord->__construct('search')
#9 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CamaController->actionAdmin()
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('admin')
#19 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('cama/admin')
#20 C:\xampp\htdocs\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Yii\test\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/yii/test/index.php?r=cama/admin
HTTP_REFERER=http://localhost:200/yii/test/index.php?r=site/login
---
